import Head from "next/head";
import Image from "next/image";
import CTABar from "components/CTABar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <CTABar />
      </div>
      {/* <div>
        <div className={styles.container}>
          <div className={styles.headingContainer}>
            <h1>Get in touch today to get a free project quote</h1>
          </div>
          <div>
            <button>Get in touch</button>
            <button>View products</button>
          </div>
        </div>
      </div> */}
    </div>
  );
}
