import Head from "next/head";
import Image from "next/image";
import CTABar from "components/CTABar";
import HeroSection from "components/HeroSection";
import AboutSection from "components/aboutSection";
import Footer from "@components/footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Alambre Cables</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroSection />
      <AboutSection />
      <CTABar />
      <Footer />
    </div>
  );
}
