import Head from "next/head";
import Image from "next/image";
import CTABar from "components/vaibhav/CTABar";
import HeroSection from "components/vaibhav/HeroSection";
import AboutSection from "@components/vaibhav/AboutSection";
import Footer from "@components/footer";
import OurProducts from "@components/vaibhav/OurProducts";
import Navbar from "@components/vaibhav/Navbar";

export default function Secondary() {
  return (
    <div>
      <Head>
        <title>Alambre Cables</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <HeroSection />
      <AboutSection />
      <OurProducts />
      <CTABar />
      <Footer />
    </div>
  );
}
