import Head from "next/head";
import CTABar from "components/CTABar";
import HeroSection from "components/HeroSection";
import AboutSection from "@components/AboutSection";
import Footer from "@components/footer";
import ProductSection from "@components/ProductSection";
import Navbar from "@components/vaibhav/Navbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Alambre Cables</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <HeroSection />
      <ProductSection />
      <AboutSection />
      <CTABar />
      <Footer />
    </div>
  );
}
